"""Type stubs for the Rust extension module ``pyraichu._pyraichu``."""

__version__: str

class ModelError(Exception): ...
class SimulationError(Exception): ...

def validate_model(model_json: str) -> None: ...
def simulate_json(
    model_json: str,
    t_max: float,
    journal: bool = False,
    confluence_check: bool = False,
    samples: list[float] | None = None,
    seed: int = 0,
    rng_stream: int = 0,
) -> str: ...
def monte_carlo_json(
    model_json: str,
    nb_runs: int,
    t_max: float,
    samples: list[float],
    seed: int = 0,
    threads: int | None = None,
    quantiles: list[float] | None = None,
) -> str: ...

class Snapshot:
    """Opaque interactive-session checkpoint (see ``Interactive``)."""

class Interactive:
    """Low-level stateful step-by-step engine (JSON in/out); wrapped by
    the Pythonic ``pyraichu.Interactive``."""

    def __init__(
        self,
        model_json: str,
        t_max: float,
        journal: bool = False,
        confluence_check: bool = False,
        seed: int = 0,
        rng_stream: int = 0,
    ) -> None: ...
    @property
    def time(self) -> float: ...
    def fireable(self) -> str: ...
    def attribute(self, qualified: str) -> str | None: ...
    def state(self, qualified: str) -> str | None: ...
    def history(self) -> str: ...
    def fire(self, name: str, to: str | None = None) -> str: ...
    def step(self) -> str | None: ...
    def set_date(self, name: str, date: float) -> None: ...
    def reset(self) -> None: ...
    def snapshot(self) -> Snapshot: ...
    def restore(self, snap: Snapshot) -> None: ...
