"""Shared settings of the emergency power supply example scripts.

Every script loads a variant of the translated model (regenerated by
`translate.py` when `model/` does not hold it yet), quantifies the
benchmark's feared event, and writes its result under `results/`: the
RAICHU envelope itself, plus a small `.meta.json` with the wall-clock time
and the machine, which the envelope does not record.
"""

from __future__ import annotations

import json
import os
import platform
import time
from contextlib import contextmanager
from pathlib import Path

import pyraichu
import translate

HERE = Path(__file__).resolve().parent
RESULTS = HERE / "results"

#: The feared event: loss of power on both bus bars LHA and LHB.
TARGET = translate.TARGET_NAME
#: Mission time of the benchmark, in hours (Bouissou 2017, section 2.1).
MISSION_TIME = translate.MISSION_TIME


def load(variant: str) -> pyraichu.Model:
    """The translated model of ``variant`` (a key of ``translate.VARIANTS``)."""
    path = translate.MODEL_DIR / f"{variant}.json"
    if not path.exists():
        translate.write(variant)
    return pyraichu.load_model(json.loads(path.read_text()))


@contextmanager
def timed(result_name: str, **settings):
    """Time the block and write ``results/<result_name>.meta.json``; the
    block may add entries to the dictionary it receives."""
    RESULTS.mkdir(exist_ok=True)
    extra: dict = {}
    start = time.perf_counter()
    yield extra
    elapsed = time.perf_counter() - start
    meta = {
        "wall_clock_s": round(elapsed, 1),
        "logical_cpus": os.cpu_count(),
        "machine": platform.processor() or platform.machine(),
        "pyraichu": pyraichu.__version__,
        **settings,
        **extra,
    }
    (RESULTS / f"{result_name}.meta.json").write_text(json.dumps(meta, indent=2) + "\n")
    print(f"{result_name}: {elapsed:.1f} s")
